/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beratbadanideal;

/**
 *
 * @author LUKMAN
 */
public class frame_badan_ideal extends javax.swing.JFrame {

    /**
     * Creates new form frame_badan_ideal
     */
    public frame_badan_ideal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        btncek = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtberat = new javax.swing.JTextField();
        txtTinggi = new javax.swing.JTextField();
        txtkeadaan = new javax.swing.JTextField();
        txtMT = new javax.swing.JTextField();
        btnprint = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ini program sederhana sekali");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        getContentPane().setLayout(null);

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Program Hitung Berat Badan Ideal");
        Title.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Title);
        Title.setBounds(110, 10, 310, 50);

        btncek.setText("Cek");
        btncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekActionPerformed(evt);
            }
        });
        getContentPane().add(btncek);
        btncek.setBounds(260, 222, 90, 40);

        jLabel1.setText("Tinggi Badan (cm)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 130, 112, 26);

        jLabel2.setText("Berat Badan (kg)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 170, 112, 26);

        jLabel3.setText("Index Massa Tubuh (IMT)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 280, 151, 26);

        jLabel4.setText("Keadaan badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 320, 88, 26);

        txtberat.setText("ini textfield");
        getContentPane().add(txtberat);
        txtberat.setBounds(240, 170, 195, 24);

        txtTinggi.setText("ini textfield");
        getContentPane().add(txtTinggi);
        txtTinggi.setBounds(240, 130, 195, 24);

        txtkeadaan.setText("ini textfield");
        getContentPane().add(txtkeadaan);
        txtkeadaan.setBounds(240, 320, 195, 24);

        txtMT.setText("ini textfield");
        getContentPane().add(txtMT);
        txtMT.setBounds(240, 280, 195, 24);

        btnprint.setText("Print");
        getContentPane().add(btnprint);
        btnprint.setBounds(360, 222, 90, 40);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 90, 110, 30);

        txtnama.setText("ini textfield");
        getContentPane().add(txtnama);
        txtnama.setBounds(240, 90, 195, 24);

        setSize(new java.awt.Dimension(525, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekActionPerformed
        float tinggi, berat, hasil, hasil2, IMT, keadaaanbdn;
        
        tinggi = Float.parseFloat(txtTinggi.getText());
        berat = Float.parseFloat(txtberat.getText());
        hasil = (float)(tinggi/100);
        hasil2 = (float)(hasil*hasil);
        IMT = (float) (berat/hasil2);
        
        txtMT.setText("" + IMT);
        
        if(IMT >=30)
               txtkeadaan.setText("Kegemukan");
            else if(IMT>=25)
            txtkeadaan.setText("agak gemuk");        
            else if(IMT>=18.5)
            txtkeadaan.setText("Tubuh Ideal");
        else
            txtkeadaan.setText("kurus");
    }//GEN-LAST:event_btncekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_badan_ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_badan_ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_badan_ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_badan_ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_badan_ideal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btncek;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMT;
    private javax.swing.JTextField txtTinggi;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txtkeadaan;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
