/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beratbadanideal;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author LUKMAN
 */
public class frame_badan_ideal extends javax.swing.JFrame {

    /**
     * Creates new form frame_badan_ideal
     */
    public frame_badan_ideal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        btncek = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtberat = new javax.swing.JTextField();
        txtTinggi = new javax.swing.JTextField();
        txtkeadaan = new javax.swing.JTextField();
        txtMT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gender2 = new javax.swing.JRadioButton();
        gender1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ini program sederhana sekali");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        getContentPane().setLayout(null);

        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Program Hitung Berat Badan Ideal");
        Title.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Title);
        Title.setBounds(110, 10, 310, 50);

        btncek.setText("Check");
        btncek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncekActionPerformed(evt);
            }
        });
        getContentPane().add(btncek);
        btncek.setBounds(460, 250, 120, 50);

        jLabel1.setText("Tinggi Badan (cm)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 160, 112, 26);

        jLabel2.setText("Berat Badan (kg)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 200, 112, 26);

        jLabel3.setText("Index Massa Tubuh (IMT)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 240, 151, 26);

        jLabel4.setText("Keadaan badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 280, 88, 26);

        txtberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtberatActionPerformed(evt);
            }
        });
        txtberat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtberatKeyTyped(evt);
            }
        });
        getContentPane().add(txtberat);
        txtberat.setBounds(240, 194, 195, 30);

        txtTinggi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTinggiKeyTyped(evt);
            }
        });
        getContentPane().add(txtTinggi);
        txtTinggi.setBounds(240, 154, 195, 30);

        txtkeadaan.setEditable(false);
        txtkeadaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkeadaanActionPerformed(evt);
            }
        });
        getContentPane().add(txtkeadaan);
        txtkeadaan.setBounds(240, 280, 195, 30);

        txtMT.setEditable(false);
        getContentPane().add(txtMT);
        txtMT.setBounds(240, 240, 195, 30);

        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 80, 110, 30);
        getContentPane().add(txtnama);
        txtnama.setBounds(240, 80, 195, 30);

        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 120, 120, 40);

        gender2.setText("Wanita");
        gender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender2ActionPerformed(evt);
            }
        });
        getContentPane().add(gender2);
        gender2.setBounds(310, 120, 111, 28);

        gender1.setText("Pria");
        gender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender1ActionPerformed(evt);
            }
        });
        getContentPane().add(gender1);
        gender1.setBounds(240, 120, 54, 28);

        jButton1.setText("New / Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 180, 120, 50);

        setSize(new java.awt.Dimension(618, 426));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncekActionPerformed
        String nama;
        float tinggi, berat, hasil, hasil2, IMT ;
        nama = txtnama.getText();
        tinggi = Float.parseFloat(txtTinggi.getText());
        berat = Float.parseFloat(txtberat.getText());

        hasil = (float)(tinggi/100); // meter convert menjadi cm 
        hasil2 = (float)(hasil*hasil);      
        IMT = (float)(berat/hasil2);

        txtMT.setText("" + IMT);

        if(IMT >=35){
            txtkeadaan.setText("Obesitas II");
        }else if (IMT >= 30){
            txtkeadaan.setText("Obesitas I");
        }else if(IMT>=25){
            txtkeadaan.setText("Kegemukan");            
        }else if(IMT>=18.5){
            txtkeadaan.setText("Tubuh Ideal");
        }else
            txtkeadaan.setText("kurus");
        JOptionPane.showMessageDialog(null, "Data "+nama+" berhasil diinput");
    }//GEN-LAST:event_btncekActionPerformed

    
    private void txtberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtberatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtberatActionPerformed

    private void txtkeadaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkeadaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkeadaanActionPerformed
    
    //clear the fields
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtnama.setText("");
        txtberat.setText("");
        txtTinggi.setText("");
        
        if(gender1.isSelected())
            gender1.setSelected(false);
        else if(gender2.isSelected())
            gender2.setSelected(false);
        
        txtkeadaan.setText("");
        txtMT.setText("");
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender2ActionPerformed
        if(gender2.isSelected())
        {
            gender1.setSelected(false);
        }
    }//GEN-LAST:event_gender2ActionPerformed

    private void gender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender1ActionPerformed
        if(gender1.isSelected())
        {
            gender2.setSelected(false);
        }
    }//GEN-LAST:event_gender1ActionPerformed

    private void txtTinggiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTinggiKeyTyped
        //mengisi txtfield hanya angka/number saja
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
        {
        evt.consume();
        } 
    }//GEN-LAST:event_txtTinggiKeyTyped

    private void txtberatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtberatKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }
        
    }//GEN-LAST:event_txtberatKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_badan_ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_badan_ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_badan_ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_badan_ideal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_badan_ideal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton btncek;
    private javax.swing.JRadioButton gender1;
    private javax.swing.JRadioButton gender2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMT;
    private javax.swing.JTextField txtTinggi;
    private javax.swing.JTextField txtberat;
    private javax.swing.JTextField txtkeadaan;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
